export const MASTER_MODULE_SEED = [
  { name: 'Document Management', key: 'DOCUMENT_MANAGEMENT' },
  { name: 'Competency Management', key: 'COMPETENCY_MANAGEMENT' },
  { name: 'My Trainings', key: 'MY_TRAININGS' },
  { name: 'Food Safety', key: 'FOOD_SAFETY' },
  { name: 'Maintenance Program', key: 'MAINTENANCE_PROGRAM' },
  { name: 'Supplier Management', key: 'SUPPLIER_MANAGEMENT' },
  { name: 'Internal Audit', key: 'INTERNAL_AUDIT' },
  { name: 'Review Meetings', key: 'REVIEW_MEETINGS' },
  { name: 'Admin Management', key: 'ADMIN_MANAGEMENT' },
  { name: 'RBAC', key: 'RBAC' },
  { name: 'Application', key: 'APP' },
] as const;

/**
 * Sub-tab / resource-group titles for each (moduleKey, resource) group.
 * Key format: `MODULE_KEY:resource` (resource must match each permission row’s `resource`).
 * Omitted keys get a title from `resourceDefaultDisplayName(resource)` when seed runs.
 * To list every key in the current seed: `node scripts/list-resource-group-keys.mjs`
 */
export const MASTER_RESOURCE_GROUP_LABELS: Partial<Record<string, string>> = {
  'ADMIN_MANAGEMENT:company': 'Company',
  'ADMIN_MANAGEMENT:department': 'Department',
  'ADMIN_MANAGEMENT:module': 'Module',
  'ADMIN_MANAGEMENT:user': 'User',

  'APP:app': 'Application',

  'DOCUMENT_MANAGEMENT:change_request': 'Change request',
  'DOCUMENT_MANAGEMENT:document': 'Document',
  'DOCUMENT_MANAGEMENT:form_records': 'Form records',
  'DOCUMENT_MANAGEMENT:list_of_forms': 'List of forms',
  'DOCUMENT_MANAGEMENT:upload_documents': 'Upload documents',

  'COMPETENCY_MANAGEMENT:employee': 'Employee',
  'COMPETENCY_MANAGEMENT:monthly_training_plan': 'Monthly training plan',
  'COMPETENCY_MANAGEMENT:personal_requisition': 'Personal requisition',
  'COMPETENCY_MANAGEMENT:trainer': 'Trainer',
  'COMPETENCY_MANAGEMENT:training': 'Training',
  'COMPETENCY_MANAGEMENT:yearly_training_plan': 'Yearly training plan',

  'MY_TRAININGS:my_training': 'My trainings',

  'SUPPLIER_MANAGEMENT:supplier': 'Supplier',

  'INTERNAL_AUDIT:conduct_audits': 'Conduct audits',
  'INTERNAL_AUDIT:corrective_action': 'Corrective action',
  'INTERNAL_AUDIT:create_checklist': 'Create checklist',
  'INTERNAL_AUDIT:internal_auditor': 'Internal auditor',
  'INTERNAL_AUDIT:monthly_auditing_plan': 'Monthly auditing plan',
  'INTERNAL_AUDIT:process_owner': 'Process owner',
  'INTERNAL_AUDIT:reports': 'Reports',
  'INTERNAL_AUDIT:yearly_auditing_plan': 'Yearly auditing plan',

  'FOOD_SAFETY:conduct_haccp': 'Conduct HACCP',
  'FOOD_SAFETY:decision_tree': 'Decision tree',
  'FOOD_SAFETY:food_safety_plan': 'Food safety plan',
  'FOOD_SAFETY:haccp_team': 'HACCP team',
  'FOOD_SAFETY:processes': 'Processes',
  'FOOD_SAFETY:product': 'Product',

  'MAINTENANCE_PROGRAM:calibration_record': 'Calibration record',
  'MAINTENANCE_PROGRAM:equipment': 'Equipment',
  'MAINTENANCE_PROGRAM:machinery': 'Machinery',
  'MAINTENANCE_PROGRAM:preventive_maintenance': 'Preventive maintenance',
  'MAINTENANCE_PROGRAM:work_request': 'Work request',

  'REVIEW_MEETINGS:meeting_participants': 'Meeting participants',
  'REVIEW_MEETINGS:mrm': 'Management review',
  'REVIEW_MEETINGS:notification': 'Notification',
  'REVIEW_MEETINGS:review_team': 'Review team',
  'REVIEW_MEETINGS:review_plan': 'Review plan',
  'REVIEW_MEETINGS:meeting_minutes': 'Minutes of meeting',

  'RBAC:rbac': 'RBAC',
};

/** One row per HTTP route. Sync paths from controllers: `node scripts/extract-secured-routes.mjs` then `node scripts/sync-master-access-paths.mjs`. */
export const MASTER_PERMISSION_SEED = [
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'create',
    key: 'EP_POST_COMPANIES_CREATE_COMPANY',
    description: 'POST /companies',
    method: 'POST',
    path: '/companies',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'view',
    key: 'EP_GET_COMPANIES_GET_ALL_COMPANIES',
    description: 'GET /companies/all',
    method: 'GET',
    path: '/companies/all',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'view',
    key: 'EP_GET_COMPANIES_GET_COMPANY',
    description: 'GET /companies/:companyId',
    method: 'GET',
    path: '/companies/:companyId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'edit',
    key: 'EP_PATCH_COMPANIES_UPDATE_COMPANY',
    description: 'PATCH /companies/:companyId',
    method: 'PATCH',
    path: '/companies/:companyId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'delete',
    key: 'EP_DELETE_COMPANIES_DELETE_COMPANY_COMPANYID',
    description: 'DELETE /companies/:companyId',
    method: 'DELETE',
    path: '/companies/:companyId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'delete',
    key: 'EP_DELETE_COMPANIES_DELETE_ALL_COMPANIES',
    description: 'DELETE /companies',
    method: 'DELETE',
    path: '/companies',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'create',
    key: 'EP_POST_COMPANIES_GET_COMPANY',
    description: 'POST /companies/get-company',
    method: 'POST',
    path: '/companies/get-company',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'company',
    action: 'create',
    key: 'EP_POST_COMPANIES_CREATE_COMPANY_WITH_FILE',
    description: 'POST /companies/create-company-with-file',
    method: 'POST',
    path: '/companies/create-company-with-file',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'create',
    key: 'EP_POST_DEPARTMENTS_CREATE_DEPARTMENT',
    description: 'POST /departments',
    method: 'POST',
    path: '/departments',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'view',
    key: 'EP_GET_DEPARTMENTS',
    description: 'GET /departments/analytics',
    method: 'GET',
    path: '/departments/analytics',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'view',
    key: 'EP_GET_DEPARTMENTS_GET_DEPARTMENT_COMPANYID',
    description: 'GET /departments/company',
    method: 'GET',
    path: '/departments/company',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'view',
    key: 'EP_GET_DEPARTMENTS_ID',
    description: 'GET /departments/:id',
    method: 'GET',
    path: '/departments/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'edit',
    key: 'EP_PATCH_DEPARTMENTS_UPDATE_DEPARTMENT',
    description: 'PATCH /departments',
    method: 'PATCH',
    path: '/departments',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'department',
    action: 'delete',
    key: 'EP_DELETE_DEPARTMENTS_DELETE_DEPARTMENT_DEPARTMENTID',
    description: 'DELETE /departments/:departmentId',
    method: 'DELETE',
    path: '/departments/:departmentId',
  },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'create',
  //   key: 'EP_POST_MODULES',
  //   description: 'POST /modules',
  //   method: 'POST',
  //   path: '/modules',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'view',
  //   key: 'EP_GET_MODULES',
  //   description: 'GET /modules',
  //   method: 'GET',
  //   path: '/modules',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'view',
  //   key: 'EP_GET_MODULES_ID',
  //   description: 'GET /modules/:id',
  //   method: 'GET',
  //   path: '/modules/:id',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'view',
  //   key: 'EP_GET_MODULES_BY_COMPANY_COMPANYID',
  //   description: 'GET /modules/by-company/:companyId',
  //   method: 'GET',
  //   path: '/modules/by-company/:companyId',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'view',
  //   key: 'EP_GET_MODULES_BY_MODULE_ID_MODULEID',
  //   description: 'GET /modules/by-module-id/:moduleId',
  //   method: 'GET',
  //   path: '/modules/by-module-id/:moduleId',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'edit',
  //   key: 'EP_PATCH_MODULES_ID',
  //   description: 'PATCH /modules/:id',
  //   method: 'PATCH',
  //   path: '/modules/:id',
  // },
  // {
  //   moduleKey: 'ADMIN_MANAGEMENT',
  //   resource: 'module',
  //   action: 'delete',
  //   key: 'EP_DELETE_MODULES_ID',
  //   description: 'DELETE /modules/:id',
  //   method: 'DELETE',
  //   path: '/modules/:id',
  // },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'create',
    key: 'EP_POST_USERS_CREATE_SUPER_ADMIN',
    description: 'POST /users/super-admin',
    method: 'POST',
    path: '/users/super-admin',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'create',
    key: 'EP_POST_USERS_CREATE_USER',
    description: 'POST /users',
    method: 'POST',
    path: '/users',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_GET_USER_USERID',
    description: 'GET /users/:id',
    method: 'GET',
    path: '/users/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_GET_USERBYCOMPANY_COMPANYID',
    description: 'GET /users/company/:companyId',
    method: 'GET',
    path: '/users/company/:companyId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_COMPANY_COMPANYID_DEPARTMENT_DEPARTMENTID',
    description: 'GET /users/company/:companyId/department/:departmentId',
    method: 'GET',
    path: '/users/company/:companyId/department/:departmentId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_GET_USERSBYDEPARTMENT_DEPARTMENTID',
    description: 'GET /users/department/:departmentId',
    method: 'GET',
    path: '/users/department/:departmentId',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_GET_ALL_USERS_DEPARTMENTID',
    description: 'GET /users/department/:departmentId/summary',
    method: 'GET',
    path: '/users/department/:departmentId/summary',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'delete',
    key: 'EP_DELETE_USERS_DELETE_USER_USERID',
    description: 'DELETE /users/:id',
    method: 'DELETE',
    path: '/users/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PUT_USERS_UPDATE_USER',
    description: 'PUT /users/:id',
    method: 'PUT',
    path: '/users/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PATCH_USERS_ASSIGN_ROLE_USERID',
    description: 'PATCH /users/:id/assign-role',
    method: 'PATCH',
    path: '/users/:id/assign-role',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'auth',
    key: 'EP_POST_USERS_USER_LOGIN',
    description: 'POST /users/login',
    method: 'POST',
    path: '/users/login',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PATCH_USERS_REASSIGN_ACCESS_USERID',
    description: 'PATCH /users/:id/reassign-access',
    method: 'PATCH',
    path: '/users/:id/reassign-access',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PATCH_USERS_SUSPEND_USER_USERID',
    description: 'PATCH /users/:id/suspend',
    method: 'PATCH',
    path: '/users/:id/suspend',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PATCH_USERS_CHANGE_PASSWORD',
    description: 'PATCH /users/:id/change-password',
    method: 'PATCH',
    path: '/users/:id/change-password',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS_ID',
    description: 'GET /users/:id',
    method: 'GET',
    path: '/users/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'view',
    key: 'EP_GET_USERS',
    description: 'GET /users',
    method: 'GET',
    path: '/users',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'edit',
    key: 'EP_PUT_USERS_ID',
    description: 'PUT /users/:id',
    method: 'PUT',
    path: '/users/:id',
  },
  {
    moduleKey: 'ADMIN_MANAGEMENT',
    resource: 'user',
    action: 'delete',
    key: 'EP_DELETE_USERS_ID',
    description: 'DELETE /users/:id',
    method: 'DELETE',
    path: '/users/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'create',
    key: 'EP_POST_CHANGE_REQUESTS_CREATE',
    description: 'POST /change-requests',
    method: 'POST',
    path: '/change-requests',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'view',
    key: 'EP_GET_CHANGE_REQUESTS_GET_ALL',
    description: 'GET /change-requests/all',
    method: 'GET',
    path: '/change-requests/all',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'view',
    key: 'EP_GET_CHANGE_REQUESTS_GET_BY_ID',
    description: 'GET /change-requests/:id',
    method: 'GET',
    path: '/change-requests/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'edit',
    key: 'EP_PUT_CHANGE_REQUESTS_UPDATE',
    description: 'PUT /change-requests/:id',
    method: 'PUT',
    path: '/change-requests/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'approve',
    key: 'EP_PATCH_CHANGE_REQUESTS_APPROVE',
    description: 'PATCH /change-requests/:id/approve',
    method: 'PATCH',
    path: '/change-requests/:id/approve',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'change_request',
    action: 'disapprove',
    key: 'EP_PATCH_CHANGE_REQUESTS_DISAPPROVE',
    description: 'PATCH /change-requests/:id/disapprove',
    method: 'PATCH',
    path: '/change-requests/:id/disapprove',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'create',
    key: 'EP_POST_DOCUMENTS_CREATE',
    description: 'POST /documents',
    method: 'POST',
    path: '/documents',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'view',
    key: 'EP_GET_DOCUMENTS_GET_ALL',
    description: 'GET /documents/all',
    method: 'GET',
    path: '/documents/all',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'view',
    key: 'EP_GET_DOCUMENTS_GET_BY_ID',
    description: 'GET /documents/:id',
    method: 'GET',
    path: '/documents/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'edit',
    key: 'EP_PUT_DOCUMENTS_UPDATE',
    description: 'PUT /documents/:id',
    method: 'PUT',
    path: '/documents/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'review',
    key: 'EP_PATCH_DOCUMENTS_REVIEW',
    description: 'PATCH /documents/:id/review',
    method: 'PATCH',
    path: '/documents/:id/review',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'approve',
    key: 'EP_PATCH_DOCUMENTS_APPROVE',
    description: 'PATCH /documents/:id/approve',
    method: 'PATCH',
    path: '/documents/:id/approve',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'reject',
    key: 'EP_PATCH_DOCUMENTS_REJECT',
    description: 'PATCH /documents/:id/reject',
    method: 'PATCH',
    path: '/documents/:id/reject',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'disapprove',
    key: 'EP_PATCH_DOCUMENTS_DISAPPROVE',
    description: 'PATCH /documents/:id/disapprove',
    method: 'PATCH',
    path: '/documents/:id/disapprove',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'document',
    action: 'edit',
    key: 'EP_PATCH_DOCUMENTS_TOGGLE_ENABLED',
    description: 'PATCH /documents/:id/toggle-enabled',
    method: 'PATCH',
    path: '/documents/:id/toggle-enabled',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'form_records',
    action: 'create',
    key: 'EP_POST_FORM_RECORDS_SUBMIT_RESPONSE',
    description: 'POST /form-records/submit-response',
    method: 'POST',
    path: '/form-records/submit-response',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'form_records',
    action: 'comment',
    key: 'EP_PATCH_FORM_RECORDS_ADDCOMMENT',
    description: 'PATCH /form-records/addComment',
    method: 'PATCH',
    path: '/form-records/addComment',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'form_records',
    action: 'verify',
    key: 'EP_PATCH_FORM_RECORDS_VERIFY_RESPONSE',
    description: 'PATCH /form-records/verify-response',
    method: 'PATCH',
    path: '/form-records/verify-response',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'form_records',
    action: 'view',
    key: 'EP_GET_FORM_RECORDS_GET_RESPONSES_BY_FORMID_FORMID_DEPARTMENTID',
    description: 'GET /form-records/get-responses-by-formId/:formId/:departmentId',
    method: 'GET',
    path: '/form-records/get-responses-by-formId/:formId/:departmentId',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'form_records',
    action: 'view',
    key: 'EP_GET_FORM_RECORDS_GET_RECORD_BY_RECORDID_RECORDID',
    description: 'GET /form-records/get-record-by-recordId/:recordId',
    method: 'GET',
    path: '/form-records/get-record-by-recordId/:recordId',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'create',
    key: 'EP_POST_FORMS_CREATE',
    description: 'POST /list-of-forms',
    method: 'POST',
    path: '/list-of-forms',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'view',
    key: 'EP_GET_FORMS_GET_ALL',
    description: 'GET /list-of-forms/all',
    method: 'GET',
    path: '/list-of-forms/all',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'view',
    key: 'EP_GET_FORMS_GET_BY_ID',
    description: 'GET /list-of-forms/:id',
    method: 'GET',
    path: '/list-of-forms/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'edit',
    key: 'EP_PUT_FORMS_UPDATE',
    description: 'PUT /list-of-forms/:id',
    method: 'PUT',
    path: '/list-of-forms/:id',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'review',
    key: 'EP_PATCH_FORMS_REVIEW',
    description: 'PATCH /list-of-forms/:id/review',
    method: 'PATCH',
    path: '/list-of-forms/:id/review',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'approve',
    key: 'EP_PATCH_FORMS_APPROVE',
    description: 'PATCH /list-of-forms/:id/approve',
    method: 'PATCH',
    path: '/list-of-forms/:id/approve',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'reject',
    key: 'EP_PATCH_FORMS_REJECT',
    description: 'PATCH /list-of-forms/:id/reject',
    method: 'PATCH',
    path: '/list-of-forms/:id/reject',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'disapprove',
    key: 'EP_PATCH_FORMS_DISAPPROVE',
    description: 'PATCH /list-of-forms/:id/disapprove',
    method: 'PATCH',
    path: '/list-of-forms/:id/disapprove',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'list_of_forms',
    action: 'edit',
    key: 'EP_PATCH_FORMS_TOGGLE_ENABLED',
    description: 'PATCH /list-of-forms/:id/toggle-enabled',
    method: 'PATCH',
    path: '/list-of-forms/:id/toggle-enabled',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'create',
    key: 'EP_POST_UPLOADDOCUMENT',
    description: 'POST /upload-documents',
    method: 'POST',
    path: '/upload-documents',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'view',
    key: 'EP_GET_READALLDOCUMENTS_DEPARTMENTID',
    description: 'GET /upload-documents/all/:departmentId',
    method: 'GET',
    path: '/upload-documents/all/:departmentId',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'view',
    key: 'EP_GET_READDOCUMENTBYID_DOCUMENTID',
    description: 'GET /upload-documents/:documentId',
    method: 'GET',
    path: '/upload-documents/:documentId',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'review',
    key: 'EP_PATCH_REVIEW_UPLOADED_DOCUMENT',
    description: 'PATCH /upload-documents/review',
    method: 'PATCH',
    path: '/upload-documents/review',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'reject',
    key: 'EP_PATCH_REJECT_UPLOADED_DOCUMENT',
    description: 'PATCH /upload-documents/reject',
    method: 'PATCH',
    path: '/upload-documents/reject',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'approve',
    key: 'EP_PATCH_APPROVE_UPLOADED_DOCUMENT',
    description: 'PATCH /upload-documents/approve',
    method: 'PATCH',
    path: '/upload-documents/approve',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'disapprove',
    key: 'EP_PATCH_DISAPPROVE_UPLOADED_DOCUMENT',
    description: 'PATCH /upload-documents/disapprove',
    method: 'PATCH',
    path: '/upload-documents/disapprove',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'comment',
    key: 'EP_PATCH_COMMENT_DOCUMENT_DOCUMENTID',
    description: 'PATCH /upload-documents/comment/:documentId',
    method: 'PATCH',
    path: '/upload-documents/comment/:documentId',
  },
  {
    moduleKey: 'DOCUMENT_MANAGEMENT',
    resource: 'upload_documents',
    action: 'edit',
    key: 'EP_PUT_REPLACEDOCUMENT_DOCUMENTID',
    description: 'PUT /upload-documents/replace/:documentId',
    method: 'PUT',
    path: '/upload-documents/replace/:documentId',
  },
  {
    moduleKey: 'APP',
    resource: 'app',
    action: 'view',
    key: 'EP_GET_ROOT',
    description: 'GET /',
    method: 'GET',
    path: '/',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'create',
    key: 'EP_POST_CONDUCT_AUDITS_ADDCONDUCTAUDIT',
    description: 'POST /conduct-audits',
    method: 'POST',
    path: '/conduct-audits',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'update',
    key: 'EP_PUT_CONDUCT_AUDITS_UPDATECONDUCTAUDIT',
    description: 'PUT /conduct-audits',
    method: 'PUT',
    path: '/conduct-audits',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'view',
    key: 'EP_GET_CONDUCT_AUDITS_READCONDUCTAUDITS_DEPARTMENTID',
    description: 'GET /conduct-audits/all/:departmentId',
    method: 'GET',
    path: '/conduct-audits/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'view',
    key: 'EP_GET_CONDUCT_AUDITS_GET_CONDUCT_AUDITS_BY_CHECKLISTID_CHECKLISTID_DEPARTMENTID',
    description: 'GET /conduct-audits/by-checklist/:checklistId/:departmentId',
    method: 'GET',
    path: '/conduct-audits/by-checklist/:checklistId/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'view',
    key: 'EP_GET_CONDUCT_AUDITS_GET_CONDUCT_AUDIT_BY_AUDITID_AUDITID',
    description: 'GET /conduct-audits/by-audit/:auditId',
    method: 'GET',
    path: '/conduct-audits/by-audit/:auditId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'delete',
    key: 'EP_DELETE_CONDUCT_AUDITS_DELETECONDUCTAUDIT',
    description: 'DELETE /conduct-audits',
    method: 'DELETE',
    path: '/conduct-audits',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'conduct_audits',
    action: 'delete',
    key: 'EP_DELETE_CONDUCT_AUDITS_DELETEALLCONDUCTAUDITS',
    description: 'DELETE /conduct-audits/all',
    method: 'DELETE',
    path: '/conduct-audits/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'create',
    key: 'EP_POST_CORRECTIVE_ACTION_ADDCORRECTIVEACTION',
    description: 'POST /corrective-action',
    method: 'POST',
    path: '/corrective-action',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'update',
    key: 'EP_PUT_CORRECTIVE_ACTION_UPDATECORRECTIVEACTION',
    description: 'PUT /corrective-action',
    method: 'PUT',
    path: '/corrective-action',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'view',
    key: 'EP_GET_CORRECTIVE_ACTION_READALLCORRECTIVEACTIONS_DEPARTMENTID',
    description: 'GET /corrective-action/all/:departmentId',
    method: 'GET',
    path: '/corrective-action/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'view',
    key: 'EP_GET_CORRECTIVE_ACTION_READCORRECTIVEACTIONBYREPORTID_REPORTID_DEPARTMENTID',
    description: 'GET /corrective-action/by-report/:reportId/:departmentId',
    method: 'GET',
    path: '/corrective-action/by-report/:reportId/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'view',
    key: 'EP_GET_CORRECTIVE_ACTION_READCORRECTIVEACTIONBYID_ACTIONID',
    description: 'GET /corrective-action/by-action/:actionId',
    method: 'GET',
    path: '/corrective-action/by-action/:actionId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'delete',
    key: 'EP_DELETE_CORRECTIVE_ACTION_DELETECORRECTIVEACTION',
    description: 'DELETE /corrective-action',
    method: 'DELETE',
    path: '/corrective-action',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'corrective_action',
    action: 'delete',
    key: 'EP_DELETE_CORRECTIVE_ACTION_DELETEALLCORRECTIVEACTIONS',
    description: 'DELETE /corrective-action/all',
    method: 'DELETE',
    path: '/corrective-action/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'create',
    key: 'EP_POST_CHECKLIST_ADDCHECKLIST',
    description: 'POST /checklist',
    method: 'POST',
    path: '/checklist',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'view',
    key: 'EP_GET_CHECKLIST_GETCHECKLISTS_DEPARTMENTID',
    description: 'GET /checklist/all/:departmentId',
    method: 'GET',
    path: '/checklist/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'view',
    key: 'EP_GET_CHECKLIST_GETCHECKLISTBYID_CHECKLISTID',
    description: 'GET /checklist/:checklistId',
    method: 'GET',
    path: '/checklist/:checklistId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'delete',
    key: 'EP_DELETE_CHECKLIST_DELETECHECKLIST',
    description: 'DELETE /checklist',
    method: 'DELETE',
    path: '/checklist',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'delete',
    key: 'EP_DELETE_CHECKLIST_DELETEALLCHECKLIST',
    description: 'DELETE /checklist/all',
    method: 'DELETE',
    path: '/checklist/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'edit',
    key: 'EP_PUT_CHECKLIST_UPDATECHECKLIST',
    description: 'PUT /checklist',
    method: 'PUT',
    path: '/checklist',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'approve',
    key: 'EP_PATCH_CHECKLIST_APPROVECHECKLIST',
    description: 'PATCH /checklist/approve',
    method: 'PATCH',
    path: '/checklist/approve',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'create_checklist',
    action: 'disapprove',
    key: 'EP_PATCH_CHECKLIST_DISAPPROVECHECKLIST',
    description: 'PATCH /checklist/disapprove',
    method: 'PATCH',
    path: '/checklist/disapprove',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'create',
    key: 'EP_POST_REPORTS_ADDREPORT',
    description: 'POST /reports',
    method: 'POST',
    path: '/reports',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'view',
    key: 'EP_GET_REPORTS_READREPORTS_DEPARTMENTID',
    description: 'GET /reports/all/:departmentId',
    method: 'GET',
    path: '/reports/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'view',
    key: 'EP_GET_REPORTS_READREPORTBYAUDITID_AUDITID_DEPARTMENTID',
    description: 'GET /reports/by-audit/:auditId/:departmentId',
    method: 'GET',
    path: '/reports/by-audit/:auditId/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'view',
    key: 'EP_GET_REPORTS_READREPORTBYID_REPORTID',
    description: 'GET /reports/:reportId',
    method: 'GET',
    path: '/reports/:reportId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'delete',
    key: 'EP_DELETE_REPORTS_DELETEREPORT',
    description: 'DELETE /reports',
    method: 'DELETE',
    path: '/reports',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'reports',
    action: 'delete',
    key: 'EP_DELETE_REPORTS_DELETEALLREPORTS',
    description: 'DELETE /reports/all',
    method: 'DELETE',
    path: '/reports/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'create',
    key: 'EP_POST_CONDUCT_HACCP_CREATE_CONDUCT_HACCP',
    description: 'POST /conduct-haccp',
    method: 'POST',
    path: '/conduct-haccp',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'view',
    key: 'EP_GET_CONDUCT_HACCP_GET_ALL_CONDUCT_HACCP_DEPARTMENTID',
    description: 'GET /conduct-haccp/all/:departmentId',
    method: 'GET',
    path: '/conduct-haccp/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'view',
    key: 'EP_GET_CONDUCT_HACCP_GET_APPROVED_CONDUCT_HACCP_DEPARTMENTID',
    description: 'GET /conduct-haccp/approved/:departmentId',
    method: 'GET',
    path: '/conduct-haccp/approved/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'view',
    key: 'EP_GET_CONDUCT_HACCP_GET_CONDUCT_HACCP_HACCPID',
    description: 'GET /conduct-haccp/:haccpId',
    method: 'GET',
    path: '/conduct-haccp/:haccpId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'delete',
    key: 'EP_DELETE_CONDUCT_HACCP_DELETE_CONDUCT_HACCP',
    description: 'DELETE /conduct-haccp',
    method: 'DELETE',
    path: '/conduct-haccp',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'delete',
    key: 'EP_DELETE_CONDUCT_HACCP_DELETE_ALL_CONDUCT_HACCP',
    description: 'DELETE /conduct-haccp/all',
    method: 'DELETE',
    path: '/conduct-haccp/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'edit',
    key: 'EP_PUT_CONDUCT_HACCP_UPDATE_CONDUCT_HACCP_HACCPID',
    description: 'PUT /conduct-haccp/:haccpId',
    method: 'PUT',
    path: '/conduct-haccp/:haccpId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'approve',
    key: 'EP_PATCH_CONDUCT_HACCP_APPROVE_CONDUCT_HACCP',
    description: 'PATCH /conduct-haccp/approve',
    method: 'PATCH',
    path: '/conduct-haccp/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'conduct_haccp',
    action: 'disapprove',
    key: 'EP_PATCH_CONDUCT_HACCP_DISAPPROVE_CONDUCT_HACCP',
    description: 'PATCH /conduct-haccp/disapprove',
    method: 'PATCH',
    path: '/conduct-haccp/disapprove',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'create',
    key: 'EP_POST_DECISION_TREE_CREATE_DECISION_TREE',
    description: 'POST /decision-tree',
    method: 'POST',
    path: '/decision-tree',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'view',
    key: 'EP_GET_DECISION_TREE_GET_ALL_DECISION_TREES_DEPARTMENTID',
    description: 'GET /decision-tree/all/:departmentId',
    method: 'GET',
    path: '/decision-tree/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'view',
    key: 'EP_GET_DECISION_TREE_GET_APPROVED_DECISION_TREES_DEPARTMENTID',
    description: 'GET /decision-tree/approved/:departmentId',
    method: 'GET',
    path: '/decision-tree/approved/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'view',
    key: 'EP_GET_DECISION_TREE_GET_DECISION_TREE_TREEID',
    description: 'GET /decision-tree/:treeId',
    method: 'GET',
    path: '/decision-tree/:treeId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'delete',
    key: 'EP_DELETE_DECISION_TREE_DELETE_DECISION_TREE',
    description: 'DELETE /decision-tree',
    method: 'DELETE',
    path: '/decision-tree',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'delete',
    key: 'EP_DELETE_DECISION_TREE_DELETE_ALL_DECISION_TREES',
    description: 'DELETE /decision-tree/all',
    method: 'DELETE',
    path: '/decision-tree/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'edit',
    key: 'EP_PATCH_DECISION_TREE_UPDATE_DECISION_TREE_TREEID',
    description: 'PATCH /decision-tree/:treeId',
    method: 'PATCH',
    path: '/decision-tree/:treeId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'approve',
    key: 'EP_PATCH_DECISION_TREE_APPROVE_DECISION_TREE',
    description: 'PATCH /decision-tree/approve',
    method: 'PATCH',
    path: '/decision-tree/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'decision_tree',
    action: 'disapprove',
    key: 'EP_PATCH_DECISION_TREE_DISAPPROVE_DECISION_TREE',
    description: 'PATCH /decision-tree/disapprove',
    method: 'PATCH',
    path: '/decision-tree/disapprove',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'create',
    key: 'EP_POST_FOOD_SAFETY_CREATE_FOOD_SAFETY',
    description: 'POST /food-safety',
    method: 'POST',
    path: '/food-safety',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'view',
    key: 'EP_GET_FOOD_SAFETY_GET_ALL_FOOD_SAFETY_DEPARTMENTID',
    description: 'GET /food-safety/all/:departmentId',
    method: 'GET',
    path: '/food-safety/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'view',
    key: 'EP_GET_FOOD_SAFETY_GET_FOOD_SAFETY_PLANID',
    description: 'GET /food-safety/:planId',
    method: 'GET',
    path: '/food-safety/:planId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'delete',
    key: 'EP_DELETE_FOOD_SAFETY_DELETE_FOOD_SAFETY',
    description: 'DELETE /food-safety',
    method: 'DELETE',
    path: '/food-safety',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'delete',
    key: 'EP_DELETE_FOOD_SAFETY_DELETE_ALL_FOOD_SAFETY',
    description: 'DELETE /food-safety/all',
    method: 'DELETE',
    path: '/food-safety/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'edit',
    key: 'EP_PATCH_FOOD_SAFETY_UPDATE_FOOD_SAFETY_PLANID',
    description: 'PATCH /food-safety/:planId',
    method: 'PATCH',
    path: '/food-safety/:planId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'approve',
    key: 'EP_PATCH_FOOD_SAFETY_APPROVE_FOOD_SAFETY',
    description: 'PATCH /food-safety/approve',
    method: 'PATCH',
    path: '/food-safety/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'food_safety_plan',
    action: 'disapprove',
    key: 'EP_PATCH_FOOD_SAFETY_DISAPPROVE_FOOD_SAFETY',
    description: 'PATCH /food-safety/disapprove',
    method: 'PATCH',
    path: '/food-safety/disapprove',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'create',
    key: 'EP_POST_HACCP_TEAM_CREATE_HACCP_TEAM',
    description: 'POST /haccp-team',
    method: 'POST',
    path: '/haccp-team',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'view',
    key: 'EP_GET_HACCP_TEAM_GET_ALL_HACCP_TEAMS_DEPARTMENTID',
    description: 'GET /haccp-team/all/:departmentId',
    method: 'GET',
    path: '/haccp-team/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'view',
    key: 'EP_GET_HACCP_TEAM_GET_APPROVED_HACCP_TEAMS_DEPARTMENTID',
    description: 'GET /haccp-team/approved/:departmentId',
    method: 'GET',
    path: '/haccp-team/approved/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'view',
    key: 'EP_GET_HACCP_TEAM_GET_HACCP_TEAM_TEAMID',
    description: 'GET /haccp-team/:teamId',
    method: 'GET',
    path: '/haccp-team/:teamId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'delete',
    key: 'EP_DELETE_HACCP_TEAM_DELETE_HACCP_TEAM_TEAMID',
    description: 'DELETE /haccp-team/:teamId',
    method: 'DELETE',
    path: '/haccp-team/:teamId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'delete',
    key: 'EP_DELETE_HACCP_TEAM_DELETE_ALL_HACCP_TEAMS',
    description: 'DELETE /haccp-team/all',
    method: 'DELETE',
    path: '/haccp-team/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'approve',
    key: 'EP_PATCH_HACCP_TEAM_APPROVEHACCPTEAM',
    description: 'PATCH /haccp-team/approve',
    method: 'PATCH',
    path: '/haccp-team/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'haccp_team',
    action: 'disapprove',
    key: 'EP_PATCH_HACCP_TEAM_DISAPPROVEHACCPTEAM',
    description: 'PATCH /haccp-team/disapprove',
    method: 'PATCH',
    path: '/haccp-team/disapprove',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'create',
    key: 'EP_POST_PROCESSES_CREATE_PROCESS',
    description: 'POST /processes',
    method: 'POST',
    path: '/processes',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'view',
    key: 'EP_GET_PROCESSES_GET_ALL_PROCESSES_DEPARTMENTID',
    description: 'GET /processes/all/:departmentId',
    method: 'GET',
    path: '/processes/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'view',
    key: 'EP_GET_PROCESSES_GET_APPROVED_PROCESSES_DEPARTMENTID',
    description: 'GET /processes/approved/:departmentId',
    method: 'GET',
    path: '/processes/approved/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'view',
    key: 'EP_GET_PROCESSES_GET_PROCESS_PROCESSID',
    description: 'GET /processes/:processId',
    method: 'GET',
    path: '/processes/:processId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'view',
    key: 'EP_GET_PROCESSES_GET_PROCESS_DETAIL_PROCESSID',
    description: 'GET /processes/detail/:processId',
    method: 'GET',
    path: '/processes/detail/:processId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'delete',
    key: 'EP_DELETE_PROCESSES_DELETE_PROCESS',
    description: 'DELETE /processes',
    method: 'DELETE',
    path: '/processes',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'delete',
    key: 'EP_DELETE_PROCESSES_DELETE_ALL_PROCESSES',
    description: 'DELETE /processes/all',
    method: 'DELETE',
    path: '/processes/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'edit',
    key: 'EP_PATCH_PROCESSES_UPDATE_PROCESS_PROCESSID',
    description: 'PATCH /processes/:processId',
    method: 'PATCH',
    path: '/processes/:processId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'approve',
    key: 'EP_PATCH_PROCESSES_APPROVE_PROCESS',
    description: 'PATCH /processes/approve',
    method: 'PATCH',
    path: '/processes/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'processes',
    action: 'disapprove',
    key: 'EP_PATCH_PROCESSES_DISAPPROVE_PROCESS',
    description: 'PATCH /processes/disapprove',
    method: 'PATCH',
    path: '/processes/disapprove',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'create',
    key: 'EP_POST_PRODUCT_CREATE_PRODUCT',
    description: 'POST /product',
    method: 'POST',
    path: '/product',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'view',
    key: 'EP_GET_PRODUCT_GET_ALL_PRODUCTS_DEPARTMENTID',
    description: 'GET /product/all/:departmentId',
    method: 'GET',
    path: '/product/all/:departmentId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'view',
    key: 'EP_GET_PRODUCT_GET_PRODUCT_PRODUCTID',
    description: 'GET /product/:productId',
    method: 'GET',
    path: '/product/:productId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'delete',
    key: 'EP_DELETE_PRODUCT_DELETE_PRODUCT_PRODUCTID',
    description: 'DELETE /product/:productId',
    method: 'DELETE',
    path: '/product/:productId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'delete',
    key: 'EP_DELETE_PRODUCT_DELETE_ALL_PRODUCTS',
    description: 'DELETE /product/all',
    method: 'DELETE',
    path: '/product/all',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'edit',
    key: 'EP_PATCH_PRODUCT_UPDATE_PRODUCT_PRODUCTID',
    description: 'PATCH /product/:productId',
    method: 'PATCH',
    path: '/product/:productId',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'approve',
    key: 'EP_PATCH_PRODUCT_APPROVE_PRODUCT',
    description: 'PATCH /product/approve',
    method: 'PATCH',
    path: '/product/approve',
  },
  {
    moduleKey: 'FOOD_SAFETY',
    resource: 'product',
    action: 'disapprove',
    key: 'EP_PATCH_PRODUCT_DISAPPROVE_PRODUCT',
    description: 'PATCH /product/disapprove',
    method: 'PATCH',
    path: '/product/disapprove',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'create',
    key: 'EP_POST_EMPLOYEES_ADDEMPLOYEE',
    description: 'POST /employees',
    method: 'POST',
    path: '/employees',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'view',
    key: 'EP_GET_EMPLOYEES_READEMPLOYEE_DEPARTMENTID',
    description: 'GET /employees/department/:departmentId',
    method: 'GET',
    path: '/employees/department/:departmentId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'view',
    key: 'EP_GET_EMPLOYEES',
    description: 'GET /employees/all',
    method: 'GET',
    path: '/employees/all',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'view',
    key: 'EP_GET_EMPLOYEES_ID',
    description: 'GET /employees/:id',
    method: 'GET',
    path: '/employees/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'edit',
    key: 'EP_PATCH_EMPLOYEES_ID',
    description: 'PATCH /employees/:id',
    method: 'PATCH',
    path: '/employees/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'create',
    key: 'EP_POST_EMPLOYEES_CREATE_EMPLOYEE_WITH_FILES',
    description: 'POST /employees/create-employee-with-files',
    method: 'POST',
    path: '/employees/create-employee-with-files',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'delete',
    key: 'EP_DELETE_EMPLOYEES_DELETEEMPLOYEE_ID',
    description: 'DELETE /employees/:id',
    method: 'DELETE',
    path: '/employees/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'employee',
    action: 'delete',
    key: 'EP_DELETE_EMPLOYEES_DELETEALLEMPLOYEES',
    description: 'DELETE /employees/all',
    method: 'DELETE',
    path: '/employees/all',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'create',
    key: 'EP_POST_MONTHLY_TRAINING_PLANS_ADDMONTHLYPLAN',
    description: 'POST /monthly-training-plans',
    method: 'POST',
    path: '/monthly-training-plans',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'view',
    key: 'EP_GET_MONTHLY_TRAINING_PLANS_READMONTHLYPLAN_DEPARTMENTID',
    description: 'GET /monthly-training-plans',
    method: 'GET',
    path: '/monthly-training-plans',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'edit',
    key: 'EP_PATCH_MONTHLY_TRAINING_PLANS_ASSIGNEMPLOYEE',
    description: 'PATCH /monthly-training-plans/assign',
    method: 'PATCH',
    path: '/monthly-training-plans/assign',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'edit',
    key: 'EP_PATCH_MONTHLY_TRAINING_PLANS_UPDATE_TRAINING_STATUS',
    description: 'PATCH /monthly-training-plans/training-status',
    method: 'PATCH',
    path: '/monthly-training-plans/training-status',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'edit',
    key: 'EP_PATCH_MONTHLY_TRAINING_PLANS_UPLOAD_IMAGES',
    description: 'PATCH /monthly-training-plans/images',
    method: 'PATCH',
    path: '/monthly-training-plans/images',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'edit',
    key: 'EP_PATCH_MONTHLY_TRAINING_PLANS_ID',
    description: 'PATCH /monthly-training-plans/:id',
    method: 'PATCH',
    path: '/monthly-training-plans/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'delete',
    key: 'EP_DELETE_MONTHLY_TRAINING_PLANS_DELETEMONTHLYPLAN_ID',
    description: 'DELETE /monthly-training-plans/:id',
    method: 'DELETE',
    path: '/monthly-training-plans/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'delete',
    key: 'EP_DELETE_MONTHLY_TRAINING_PLANS_DELETEALLMONTHLYPLANS',
    description: 'DELETE /monthly-training-plans/all',
    method: 'DELETE',
    path: '/monthly-training-plans/all',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'view',
    key: 'EP_GET_MONTHLY_TRAINING_PLANS_ANALYTICS',
    description: 'GET /monthly-training-plans/analytics',
    method: 'GET',
    path: '/monthly-training-plans/analytics',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'monthly_training_plan',
    action: 'view',
    key: 'EP_GET_MONTHLY_TRAINING_PLANS_RECORD_DETAILS',
    description: 'GET /monthly-training-plans/record-details/:id',
    method: 'GET',
    path: '/monthly-training-plans/record-details/:id',
  },
  {
    moduleKey: 'MY_TRAININGS',
    resource: 'my_training',
    action: 'view',
    key: 'EP_GET_MY_TRAININGS_ASSIGNED',
    description: 'GET /monthly-training-plans/assigned',
    method: 'GET',
    path: '/monthly-training-plans/assigned',
  },
  {
    moduleKey: 'MY_TRAININGS',
    resource: 'my_training',
    action: 'edit',
    key: 'EP_PATCH_MY_TRAININGS_EVALUATE',
    description: 'PATCH /monthly-training-plans/evaluate',
    method: 'PATCH',
    path: '/monthly-training-plans/evaluate',
  },
  {
    moduleKey: 'MY_TRAININGS',
    resource: 'my_training',
    action: 'edit',
    key: 'EP_PATCH_MY_TRAININGS_CONDUCT_EMPLOYEE',
    description: 'PATCH /monthly-training-plans/conduct-employee',
    method: 'PATCH',
    path: '/monthly-training-plans/conduct-employee',
  },
  {
    moduleKey: 'MY_TRAININGS',
    resource: 'trainer',
    action: 'view',
    key: 'EP_GET_TRAINERS_ME',
    description: 'GET /trainers/me',
    method: 'GET',
    path: '/trainers/me',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'create',
    key: 'EP_POST_PERSONAL_REQUISITIONS_ADDPERSONALRECUISITION',
    description: 'POST /personal-requisitions',
    method: 'POST',
    path: '/personal-requisitions',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'view',
    key: 'EP_GET_PERSONAL_REQUISITIONS_READPERSONALRECUISITION_DEPARTMENTID',
    description: 'GET /personal-requisitions/:departmentId',
    method: 'GET',
    path: '/personal-requisitions/:departmentId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'view',
    key: 'EP_GET_PERSONAL_REQUISITIONS_READALLPERSONALRECUISITION_COMPANYID',
    description: 'GET /personal-requisitions/all/:companyId',
    method: 'GET',
    path: '/personal-requisitions/all/:companyId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'edit',
    key: 'EP_PATCH_PERSONAL_REQUISITIONS_UPDATEPERSONSTATUS',
    description: 'PATCH /personal-requisitions',
    method: 'PATCH',
    path: '/personal-requisitions',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'delete',
    key: 'EP_DELETE_PERSONAL_REQUISITIONS_DELETEPERSONALREQUISITION_ID',
    description: 'DELETE /personal-requisitions/:id',
    method: 'DELETE',
    path: '/personal-requisitions/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'personal_requisition',
    action: 'delete',
    key: 'EP_DELETE_PERSONAL_REQUISITIONS_DELETEALLPERSONALRECUISION',
    description: 'DELETE /personal-requisitions/all',
    method: 'DELETE',
    path: '/personal-requisitions/all',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'create',
    key: 'EP_POST_SUPPLIERS_CREATE_SUPPLIER',
    description: 'POST /suppliers',
    method: 'POST',
    path: '/suppliers',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'view',
    key: 'EP_GET_SUPPLIERS_GET_ALL_SUPPLIERS_DEPARTMENTID',
    description: 'GET /suppliers/all/:departmentId',
    method: 'GET',
    path: '/suppliers/all/:departmentId',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'view',
    key: 'EP_GET_SUPPLIERS_GET_SUPPLIER_SUPPLIERID',
    description: 'GET /suppliers/:id',
    method: 'GET',
    path: '/suppliers/:id',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'delete',
    key: 'EP_DELETE_SUPPLIERS_DELETE_SUPPLIER',
    description: 'DELETE /suppliers',
    method: 'DELETE',
    path: '/suppliers',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'delete',
    key: 'EP_DELETE_SUPPLIERS_DELETE_ALL_SUPPLIERS',
    description: 'DELETE /suppliers/all',
    method: 'DELETE',
    path: '/suppliers/all',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'approve',
    key: 'EP_PATCH_SUPPLIERS_APPROVE_SUPPLIER',
    description: 'PATCH /suppliers/approve',
    method: 'PATCH',
    path: '/suppliers/approve',
  },
  {
    moduleKey: 'SUPPLIER_MANAGEMENT',
    resource: 'supplier',
    action: 'disapprove',
    key: 'EP_PATCH_SUPPLIERS_DISAPPROVE_SUPPLIER',
    description: 'PATCH /suppliers/disapprove',
    method: 'PATCH',
    path: '/suppliers/disapprove',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'create',
    key: 'EP_POST_TRAINERS_ADDTRAINER',
    description: 'POST /trainers',
    method: 'POST',
    path: '/trainers',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'view',
    key: 'EP_GET_TRAINERS_READTRAINER_DEPARTMENTID',
    description: 'GET /trainers/:departmentId',
    method: 'GET',
    path: '/trainers/:departmentId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'edit',
    key: 'EP_PATCH_TRAINERS_TRAINER_ASSIGN_TABS_TRAINERID',
    description: 'PATCH /trainers/trainer/assign-tabs/:trainerId',
    method: 'PATCH',
    path: '/trainers/trainer/assign-tabs/:trainerId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'edit',
    key: 'EP_PATCH_TRAINERS_ID',
    description: 'PATCH /trainers/:id',
    method: 'PATCH',
    path: '/trainers/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'delete',
    key: 'EP_DELETE_TRAINERS_DELETETRAINER_ID',
    description: 'DELETE /trainers/:id',
    method: 'DELETE',
    path: '/trainers/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'trainer',
    action: 'delete',
    key: 'EP_DELETE_TRAINERS_DELETEALLTRAINERS',
    description: 'DELETE /trainers/all',
    method: 'DELETE',
    path: '/trainers/all',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'training',
    action: 'create',
    key: 'EP_POST_TRAININGS_ADDTRAINING',
    description: 'POST /trainings',
    method: 'POST',
    path: '/trainings',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'training',
    action: 'view',
    key: 'EP_GET_TRAININGS_READTRAINING_DEPARTMENTID',
    description: 'GET /trainings/:departmentId',
    method: 'GET',
    path: '/trainings/:departmentId',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'training',
    action: 'edit',
    key: 'EP_PATCH_TRAININGS_ID',
    description: 'PATCH /trainings/:id',
    method: 'PATCH',
    path: '/trainings/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'training',
    action: 'delete',
    key: 'EP_DELETE_TRAININGS_DELETETRAINING_ID',
    description: 'DELETE /trainings/:id',
    method: 'DELETE',
    path: '/trainings/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'training',
    action: 'delete',
    key: 'EP_DELETE_TRAININGS_DELETEALLTRAININGS',
    description: 'DELETE /trainings/all',
    method: 'DELETE',
    path: '/trainings/all',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'yearly_training_plan',
    action: 'create',
    key: 'EP_POST_YEARLY_TRAINING_PLANS_ADDYEARLYPLAN',
    description: 'POST /yearly-training-plans',
    method: 'POST',
    path: '/yearly-training-plans',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'yearly_training_plan',
    action: 'view',
    key: 'EP_GET_YEARLY_TRAINING_PLANS_READYEARLYPLAN_DEPARTMENTID',
    description: 'GET /yearly-training-plans',
    method: 'GET',
    path: '/yearly-training-plans',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'yearly_training_plan',
    action: 'edit',
    key: 'EP_PATCH_YEARLY_TRAINING_PLANS_ID',
    description: 'PATCH /yearly-training-plans/:id',
    method: 'PATCH',
    path: '/yearly-training-plans/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'yearly_training_plan',
    action: 'delete',
    key: 'EP_DELETE_YEARLY_TRAINING_PLANS_DELETEYEARLYPLAN_ID',
    description: 'DELETE /yearly-training-plans/:id',
    method: 'DELETE',
    path: '/yearly-training-plans/:id',
  },
  {
    moduleKey: 'COMPETENCY_MANAGEMENT',
    resource: 'yearly_training_plan',
    action: 'delete',
    key: 'EP_DELETE_YEARLY_TRAINING_PLANS_DELETEALLYEARLYPLANS',
    description: 'DELETE /yearly-training-plans/all',
    method: 'DELETE',
    path: '/yearly-training-plans/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'internal_auditor',
    action: 'create',
    key: 'EP_POST_INTERNAL_AUDITOR_ADDAUDITOR',
    description: 'POST /internal-auditor',
    method: 'POST',
    path: '/internal-auditor',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'internal_auditor',
    action: 'view',
    key: 'EP_GET_INTERNAL_AUDITOR_READAUDITOR_DEPARTMENTID',
    description: 'GET /internal-auditor/all/:departmentId',
    method: 'GET',
    path: '/internal-auditor/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'internal_auditor',
    action: 'delete',
    key: 'EP_DELETE_INTERNAL_AUDITOR_DELETEAUDITOR',
    description: 'DELETE /internal-auditor',
    method: 'DELETE',
    path: '/internal-auditor',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'internal_auditor',
    action: 'delete',
    key: 'EP_DELETE_INTERNAL_AUDITOR_DELETEALLAUDITORS',
    description: 'DELETE /internal-auditor/all',
    method: 'DELETE',
    path: '/internal-auditor/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'monthly_auditing_plan',
    action: 'create',
    key: 'EP_POST_MONTHLY_AUDIT_PLAN_ADDMONTHLYAUDITINGPLAN',
    description: 'POST /monthly-audit-plan',
    method: 'POST',
    path: '/monthly-audit-plan',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'monthly_auditing_plan',
    action: 'view',
    key: 'EP_GET_MONTHLY_AUDIT_PLAN_READMONTHLYAUDITPLAN_DEPARTMENTID',
    description: 'GET /monthly-audit-plan/:departmentId',
    method: 'GET',
    path: '/monthly-audit-plan/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'monthly_auditing_plan',
    action: 'view',
    key: 'EP_GET_MONTHLY_AUDIT_PLAN_READMONTHLYAUDITPLANBYID_PLANID',
    description: 'GET /monthly-audit-plan/:planId',
    method: 'GET',
    path: '/monthly-audit-plan/:planId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'monthly_auditing_plan',
    action: 'delete',
    key: 'EP_DELETE_MONTHLY_AUDIT_PLAN_DELETEMONTHLYPLAN',
    description: 'DELETE /monthly-audit-plan',
    method: 'DELETE',
    path: '/monthly-audit-plan',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'process_owner',
    action: 'create',
    key: 'EP_POST_PROCESS_OWNER_ADDPROCESS',
    description: 'POST /process-owner',
    method: 'POST',
    path: '/process-owner',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'process_owner',
    action: 'view',
    key: 'EP_GET_PROCESS_OWNER_READPROCESS_DEPARTMENTID',
    description: 'GET /process-owner/all/:departmentId',
    method: 'GET',
    path: '/process-owner/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'process_owner',
    action: 'delete',
    key: 'EP_DELETE_PROCESS_OWNER_DELETEPROCESS_PROCESSID',
    description: 'DELETE /process-owner/:processId',
    method: 'DELETE',
    path: '/process-owner/:processId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'process_owner',
    action: 'delete',
    key: 'EP_DELETE_PROCESS_OWNER_DELETEALLPROCESSES',
    description: 'DELETE /process-owner/all',
    method: 'DELETE',
    path: '/process-owner/all',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'create',
    key: 'EP_POST_YEARLY_AUDIT_PLAN_ADDYEARLYAUDITPLAN',
    description: 'POST /yearly-audit-plan',
    method: 'POST',
    path: '/yearly-audit-plan',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'edit',
    key: 'EP_PUT_YEARLY_AUDIT_PLAN_EDITYEARLYAUDITPLAN',
    description: 'PUT /yearly-audit-plan/:planId',
    method: 'PUT',
    path: '/yearly-audit-plan/:planId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'view',
    key: 'EP_GET_YEARLY_AUDIT_PLAN_READYEARLYAUDITPLAN_DEPARTMENTID',
    description: 'GET /yearly-audit-plan/all/:departmentId',
    method: 'GET',
    path: '/yearly-audit-plan/all/:departmentId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'view',
    key: 'EP_GET_YEARLY_AUDIT_PLAN_READYEARLYAUDITPLANBYID_PLANID',
    description: 'GET /yearly-audit-plan/:planId',
    method: 'GET',
    path: '/yearly-audit-plan/:planId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'delete',
    key: 'EP_DELETE_YEARLY_AUDIT_PLAN_DELETEYEARLYAUDITPLAN_PLANID',
    description: 'DELETE /yearly-audit-plan/:planId',
    method: 'DELETE',
    path: '/yearly-audit-plan/:planId',
  },
  {
    moduleKey: 'INTERNAL_AUDIT',
    resource: 'yearly_auditing_plan',
    action: 'delete',
    key: 'EP_DELETE_YEARLY_AUDIT_PLAN_DELETEALLYEARLYAUDITPLANS',
    description: 'DELETE /yearly-audit-plan/all',
    method: 'DELETE',
    path: '/yearly-audit-plan/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'mrm',
    action: 'create',
    key: 'EP_POST_MRM_CREATE_MRM',
    description: 'POST /mrm',
    method: 'POST',
    path: '/mrm',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'mrm',
    action: 'view',
    key: 'EP_GET_MRM_GET_ALL_MRMS_DEPARTMENTID',
    description: 'GET /mrm/all/:departmentId',
    method: 'GET',
    path: '/mrm/all/:departmentId',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'mrm',
    action: 'view',
    key: 'EP_GET_MRM_GET_MRMBYID_MRMID',
    description: 'GET /mrm/:id',
    method: 'GET',
    path: '/mrm/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'mrm',
    action: 'delete',
    key: 'EP_DELETE_MRM_DELETE_MRM',
    description: 'DELETE /mrm',
    method: 'DELETE',
    path: '/mrm',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'mrm',
    action: 'delete',
    key: 'EP_DELETE_MRM_DELETE_ALL_MRMS',
    description: 'DELETE /mrm/all',
    method: 'DELETE',
    path: '/mrm/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'notification',
    action: 'create',
    key: 'EP_POST_NOTIFICATION_CREATE_NOTIFICATION',
    description: 'POST /notification',
    method: 'POST',
    path: '/notification',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'notification',
    action: 'view',
    key: 'EP_GET_NOTIFICATION_GET_ALL_NOTIFICATIONS_DEPARTMENTID',
    description: 'GET /notification/all/:departmentId',
    method: 'GET',
    path: '/notification/all/:departmentId',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'notification',
    action: 'view',
    key: 'EP_GET_NOTIFICATION_GET_NOTIFICATION',
    description: 'GET /notification/:id',
    method: 'GET',
    path: '/notification/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'notification',
    action: 'delete',
    key: 'EP_DELETE_NOTIFICATION_DELETE_NOTIFICATION',
    description: 'DELETE /notification',
    method: 'DELETE',
    path: '/notification',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'notification',
    action: 'delete',
    key: 'EP_DELETE_NOTIFICATION_DELETE_ALL_NOTIFICATIONS',
    description: 'DELETE /notification/all',
    method: 'DELETE',
    path: '/notification/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'create',
    key: 'EP_POST_PARTICIPANTS_CREATE_PARTICIPANTS',
    description: 'POST /meeting-participants',
    method: 'POST',
    path: '/meeting-participants',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'view',
    key: 'EP_GET_PARTICIPANTS_GET_ALL_PARTICIPANTS_DEPARTMENTID',
    description: 'GET /meeting-participants/all/:departmentId',
    method: 'GET',
    path: '/meeting-participants/all/:departmentId',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'view',
    key: 'EP_GET_PARTICIPANTS_GET_PARTICIPANT',
    description: 'GET /meeting-participants/:id',
    method: 'GET',
    path: '/meeting-participants/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'delete',
    key: 'EP_DELETE_PARTICIPANTS_DELETE_PARTICIPANTS',
    description: 'DELETE /meeting-participants',
    method: 'DELETE',
    path: '/meeting-participants',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'delete',
    key: 'EP_DELETE_PARTICIPANTS_DELETE_ALL_PARTICIPANTS',
    description: 'DELETE /meeting-participants/all',
    method: 'DELETE',
    path: '/meeting-participants/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_participants',
    action: 'edit',
    key: 'EP_PUT_PARTICIPANTS_UPDATE_PARTICIPANTS',
    description: 'PUT /meeting-participants/:id',
    method: 'PUT',
    path: '/meeting-participants/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'create',
    key: 'EP_POST_REVIEW_TEAM_CREATE_MEMBER',
    description: 'POST /review-team',
    method: 'POST',
    path: '/review-team',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'create',
    key: 'EP_POST_REVIEW_TEAM_CREATE_MEMBERS_BULK',
    description: 'POST /review-team/bulk',
    method: 'POST',
    path: '/review-team/bulk',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'view',
    key: 'EP_GET_REVIEW_TEAM_GET_ALL_MEMBERS',
    description: 'GET /review-team/all',
    method: 'GET',
    path: '/review-team/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'view',
    key: 'EP_GET_REVIEW_TEAM_GET_MEMBER',
    description: 'GET /review-team/:id',
    method: 'GET',
    path: '/review-team/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'edit',
    key: 'EP_PUT_REVIEW_TEAM_UPDATE_MEMBER',
    description: 'PUT /review-team/:id',
    method: 'PUT',
    path: '/review-team/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_team',
    action: 'delete',
    key: 'EP_DELETE_REVIEW_TEAM_DELETE_MEMBER',
    description: 'DELETE /review-team/:id',
    method: 'DELETE',
    path: '/review-team/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_plan',
    action: 'create',
    key: 'EP_POST_REVIEW_PLANS_CREATE_PLAN',
    description: 'POST /review-plans',
    method: 'POST',
    path: '/review-plans',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_plan',
    action: 'view',
    key: 'EP_GET_REVIEW_PLANS_GET_ALL_PLANS',
    description: 'GET /review-plans/all',
    method: 'GET',
    path: '/review-plans/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_plan',
    action: 'view',
    key: 'EP_GET_REVIEW_PLANS_GET_PLAN',
    description: 'GET /review-plans/:id',
    method: 'GET',
    path: '/review-plans/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_plan',
    action: 'edit',
    key: 'EP_PUT_REVIEW_PLANS_UPDATE_PLAN',
    description: 'PUT /review-plans/:id',
    method: 'PUT',
    path: '/review-plans/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'review_plan',
    action: 'delete',
    key: 'EP_DELETE_REVIEW_PLANS_DELETE_PLAN',
    description: 'DELETE /review-plans/:id',
    method: 'DELETE',
    path: '/review-plans/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'create',
    key: 'EP_POST_MEETING_MINUTES_CREATE_MINUTES',
    description: 'POST /meeting-minutes',
    method: 'POST',
    path: '/meeting-minutes',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'view',
    key: 'EP_GET_MEETING_MINUTES_GET_ALL_MINUTES',
    description: 'GET /meeting-minutes/all',
    method: 'GET',
    path: '/meeting-minutes/all',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'view',
    key: 'EP_GET_MEETING_MINUTES_GET_MINUTES_BY_PLAN',
    description: 'GET /meeting-minutes/by-plan/:planId',
    method: 'GET',
    path: '/meeting-minutes/by-plan/:planId',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'view',
    key: 'EP_GET_MEETING_MINUTES_GET_MINUTES',
    description: 'GET /meeting-minutes/:id',
    method: 'GET',
    path: '/meeting-minutes/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'edit',
    key: 'EP_PUT_MEETING_MINUTES_UPDATE_MINUTES',
    description: 'PUT /meeting-minutes/:id',
    method: 'PUT',
    path: '/meeting-minutes/:id',
  },
  {
    moduleKey: 'REVIEW_MEETINGS',
    resource: 'meeting_minutes',
    action: 'delete',
    key: 'EP_DELETE_MEETING_MINUTES_DELETE_MINUTES',
    description: 'DELETE /meeting-minutes/:id',
    method: 'DELETE',
    path: '/meeting-minutes/:id',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'create',
    key: 'EP_POST_RBAC_SEED_MASTER_DATA',
    description: 'POST /rbac/seed-master-data',
    method: 'POST',
    path: '/rbac/seed-master-data',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_MASTER_MODULES',
    description: 'GET /rbac/master-modules',
    method: 'GET',
    path: '/rbac/master-modules',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_MASTER_PERMISSIONS',
    description: 'GET /rbac/master-permissions',
    method: 'GET',
    path: '/rbac/master-permissions',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_MASTER_PERMISSIONS_MODULE_MODULEID',
    description: 'GET /rbac/master-permissions/module/:moduleId',
    method: 'GET',
    path: '/rbac/master-permissions/module/:moduleId',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_PERMISSION_TREE',
    description: 'GET /rbac/permission-tree',
    method: 'GET',
    path: '/rbac/permission-tree',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'create',
    key: 'EP_POST_RBAC_ROLES',
    description: 'POST /rbac/roles',
    method: 'POST',
    path: '/rbac/roles',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_ROLES',
    description: 'GET /rbac/roles',
    method: 'GET',
    path: '/rbac/roles',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_ROLES_COMPANY_COMPANYID',
    description: 'GET /rbac/roles/company/:companyId',
    method: 'GET',
    path: '/rbac/roles/company/:companyId',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'edit',
    key: 'EP_PATCH_RBAC_ASSIGN_ROLE',
    description: 'PATCH /rbac/assign-role',
    method: 'PATCH',
    path: '/rbac/assign-role',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_MASTER_MODULE_DETAILS_MASTERMODULEID',
    description: 'GET /rbac/master-modules/:masterModuleId/details',
    method: 'GET',
    path: '/rbac/master-modules/:masterModuleId/details',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_MASTER_RESOURCES',
    description: 'GET /rbac/master-resources',
    method: 'GET',
    path: '/rbac/master-resources',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'create',
    key: 'EP_POST_RBAC_DERIVED_MODULES',
    description: 'POST /rbac/derived-modules',
    method: 'POST',
    path: '/rbac/derived-modules',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_DERIVED_MODULES',
    description: 'GET /rbac/derived-modules',
    method: 'GET',
    path: '/rbac/derived-modules',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'view',
    key: 'EP_GET_RBAC_DERIVED_MODULE_BY_ID',
    description: 'GET /rbac/derived-modules/:derivedModuleId',
    method: 'GET',
    path: '/rbac/derived-modules/:derivedModuleId',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'edit',
    key: 'EP_PATCH_RBAC_DERIVED_MODULE_BY_ID',
    description: 'PATCH /rbac/derived-modules/:derivedModuleId',
    method: 'PATCH',
    path: '/rbac/derived-modules/:derivedModuleId',
  },
  {
    moduleKey: 'RBAC',
    resource: 'rbac',
    action: 'delete',
    key: 'EP_DELETE_RBAC_DERIVED_MODULE_BY_ID',
    description: 'DELETE /rbac/derived-modules/:derivedModuleId',
    method: 'DELETE',
    path: '/rbac/derived-modules/:derivedModuleId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'calibration_record',
    action: 'create',
    key: 'EP_POST_ADDCALIBRATION_EQUIPMENTID',
    description: 'POST /calibration-record/:equipmentId',
    method: 'POST',
    path: '/calibration-record/:equipmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'calibration_record',
    action: 'view',
    key: 'EP_GET_READALLCALIBRATION_DEPARTMENTID',
    description: 'GET /calibration-record/all/:departmentId',
    method: 'GET',
    path: '/calibration-record/all/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'calibration_record',
    action: 'view',
    key: 'EP_GET_READCALIBRATIONBYEQUIPMENTID_EQUIPMENTID_DEPARTMENTID',
    description: 'GET /calibration-record/by-equipment/:equipmentId/:departmentId',
    method: 'GET',
    path: '/calibration-record/by-equipment/:equipmentId/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'equipment',
    action: 'create',
    key: 'EP_POST_EQUIPMENT_ADDEQUIPMENT',
    description: 'PATCH /equipments/:id',
    method: 'PATCH',
    path: '/equipments/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'equipment',
    action: 'view',
    key: 'EP_GET_EQUIPMENT_READALLEQUIPMENT_DEPARTMENTID',
    description: 'GET /equipments/all/:departmentId',
    method: 'GET',
    path: '/equipments/all/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'equipment',
    action: 'view',
    key: 'EP_GET_EQUIPMENT_READEQUIPMENT_ID',
    description: 'GET /equipments/:id',
    method: 'GET',
    path: '/equipments/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'equipment',
    action: 'delete',
    key: 'EP_DELETE_EQUIPMENT_DELETEEQUIPMENT_ID',
    description: 'DELETE /equipments/:id',
    method: 'DELETE',
    path: '/equipments/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'equipment',
    action: 'delete',
    key: 'EP_DELETE_EQUIPMENT_DELETEALLEQUIPMENT',
    description: 'DELETE /equipments/all',
    method: 'DELETE',
    path: '/equipments/all',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'machinery',
    action: 'create',
    key: 'EP_POST_MACHINERY_ADDMACHINERY',
    description: 'PATCH /machines/:id',
    method: 'PATCH',
    path: '/machines/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'machinery',
    action: 'view',
    key: 'EP_GET_MACHINERY_READALLMACHINERY_DEPARTMENTID',
    description: 'GET /machines/all/:departmentId',
    method: 'GET',
    path: '/machines/all/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'machinery',
    action: 'view',
    key: 'EP_GET_MACHINERY_READMACHINERY_ID',
    description: 'GET /machines/:id',
    method: 'GET',
    path: '/machines/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'machinery',
    action: 'delete',
    key: 'EP_DELETE_MACHINERY_DELETEMACHINERY_ID',
    description: 'DELETE /machines/:id',
    method: 'DELETE',
    path: '/machines/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'machinery',
    action: 'delete',
    key: 'EP_DELETE_MACHINERY_DELETEALLMACHINERY',
    description: 'DELETE /machines/all',
    method: 'DELETE',
    path: '/machines/all',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'create',
    key: 'EP_POST_ADDPREVENTIVEMAINTAINCE_MACHINEID',
    description: 'POST /preventive-maintenance/:machineId',
    method: 'POST',
    path: '/preventive-maintenance/:machineId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'view',
    key: 'EP_GET_GETALLMAINTENANCERECORDS_DEPARTMENTID',
    description: 'GET /preventive-maintenance/all/:departmentId',
    method: 'GET',
    path: '/preventive-maintenance/all/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'view',
    key: 'EP_GET_GETMAINTENANCEBYMACHINEID_MACHINEID_DEPARTMENTID',
    description: 'GET /preventive-maintenance/by-machine/:machineId/:departmentId',
    method: 'GET',
    path: '/preventive-maintenance/by-machine/:machineId/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'view',
    key: 'EP_GET_GETMAINTENANCEBYID_MAINTAINANCEID',
    description: 'GET /preventive-maintenance/:id',
    method: 'GET',
    path: '/preventive-maintenance/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'delete',
    key: 'EP_DELETE_DELETEALLMAINTENANCERECORDS',
    description: 'DELETE /preventive-maintenance/all',
    method: 'DELETE',
    path: '/preventive-maintenance/all',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'preventive_maintenance',
    action: 'delete',
    key: 'EP_DELETE_DELETEMAINTENANCEBYID_MAINTAINANCEID',
    description: 'DELETE /preventive-maintenance/:id',
    method: 'DELETE',
    path: '/preventive-maintenance/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'create',
    key: 'EP_POST_CREATEWORKREQUEST',
    description: 'POST /work-requests',
    method: 'POST',
    path: '/work-requests',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'reject',
    key: 'EP_PATCH_REJECTMWR_ID',
    description: 'PATCH /work-requests/:id/reject',
    method: 'PATCH',
    path: '/work-requests/:id/reject',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'accept',
    key: 'EP_PATCH_ACCEPTMWR_ID',
    description: 'PATCH /work-requests/:id/accept',
    method: 'PATCH',
    path: '/work-requests/:id/accept',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'complete',
    key: 'EP_PATCH_COMPLETEMWR_ID',
    description: 'PATCH /work-requests/:id/complete',
    method: 'PATCH',
    path: '/work-requests/:id/complete',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'view',
    key: 'EP_GET_GETALLWORKREQUESTS_DEPARTMENTID',
    description: 'GET /work-requests/all/:departmentId',
    method: 'GET',
    path: '/work-requests/all/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'view',
    key: 'EP_GET_GETWORKREQUESTBYID_ID',
    description: 'GET /work-requests/:id',
    method: 'GET',
    path: '/work-requests/:id',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'view',
    key: 'EP_GET_GETWORKREQUESTSBYMACHINEID_MACHINEID_DEPARTMENTID',
    description: 'GET /work-requests/by-machine/:machineId/:departmentId',
    method: 'GET',
    path: '/work-requests/by-machine/:machineId/:departmentId',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'delete',
    key: 'EP_DELETE_DELETEALLWORKREQUESTS',
    description: 'DELETE /work-requests/all',
    method: 'DELETE',
    path: '/work-requests/all',
  },
  {
    moduleKey: 'MAINTENANCE_PROGRAM',
    resource: 'work_request',
    action: 'delete',
    key: 'EP_DELETE_DELETEWORKREQUESTBYID_ID',
    description: 'DELETE /work-requests/:id',
    method: 'DELETE',
    path: '/work-requests/:id',
  },
] as const;
